from fastapi import APIRouter, Depends, status, Query, Path, HTTPException, Request
from typing import Optional, Any
from asyncpg import Connection
from uuid import UUID
from src.security.cookies import require_admin_access
from src.schemas.log import SystemLogResponse
from src.db import db_connection
from src.ratelimit import limiter


router = APIRouter(dependencies=[Depends(require_admin_access)])


@router.get("/", response_model=list[SystemLogResponse])
@limiter.limit("16/minute")
async def list_logs(
    request: Request,
    limit: int = Query(default=50, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
    error_level: Optional[str] = Query(default=None, description="Filter by ERROR, WARNING, CRITICAL, INFO"),
    error_type: Optional[str] = Query(default=None, description="Exact match for the exception type"),
    user_id: Optional[UUID] = Query(default=None, description="Filter logs generated by a specific user"),
    conn: Connection = Depends(db_connection)
):
    conditions = []
    params: list[Any] = []
    
    if error_level:
        params.append(error_level)
        conditions.append(f"error_level = ${len(params)}")
        
    if user_id:
        params.append(user_id)
        conditions.append(f"user_id = ${len(params)}")
        
    if error_type:
        params.append(error_type)
        conditions.append(f"error_type = ${len(params)}")

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    params.extend([limit, offset])
    
    # Cast ip_address to TEXT to ensure compatibility with Pydantic
    query = f"""
        SELECT 
            id, user_id, ip_address::TEXT as ip_address, user_agent, 
            request_method, request_path, error_level, error_type, 
            error_message, failed_query, query_parameters, execution_context, 
            stack_trace, created_at
        FROM 
            system_logs
        {where_clause}
        ORDER BY 
            created_at DESC
        LIMIT ${len(params) - 1} 
        OFFSET ${len(params)};
    """
    
    rows = await conn.fetch(query, *params)

    return [dict(row) for row in rows]


@router.get("/{log_id}", response_model=SystemLogResponse)
@limiter.limit("16/minute")
async def get_log_details(
    request: Request,
    log_id: UUID = Path(...),
    conn: Connection = Depends(db_connection)
):
    query = """
        SELECT 
            id, user_id, ip_address::TEXT as ip_address, user_agent, 
            request_method, request_path, error_level, error_type, 
            error_message, failed_query, query_parameters, execution_context, 
            stack_trace, created_at
        FROM 
            system_logs
        WHERE 
            id = $1;
    """
    
    row = await conn.fetchrow(query, log_id)
    
    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Log entry not found."
        )
        
    return dict(row)


@router.delete("/{log_id}", status_code=status.HTTP_204_NO_CONTENT)
@limiter.limit("16/minute")
async def delete_log(request: Request, log_id: UUID = Path(...), conn: Connection = Depends(db_connection)):
    query = "DELETE FROM system_logs WHERE id = $1 RETURNING id;"
    deleted_id = await conn.fetchval(query, log_id)
    
    if not deleted_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Log entry not found."
        )


@router.delete("/", status_code=status.HTTP_204_NO_CONTENT)
@limiter.limit("16/minute")
async def clear_old_logs(
    request: Request,
    days_to_keep: int = Query(default=30, ge=0, description="Delete logs older than this many days. Use 0 to delete all logs."),
    conn: Connection = Depends(db_connection)
):
    if days_to_keep == 0:
        # Warning: This truncates the entire table. Only admins can do this, 
        # but you might want to add an extra confirmation layer in the frontend.
        await conn.execute("TRUNCATE TABLE system_logs;")
    else:
        query = "DELETE FROM system_logs WHERE created_at < NOW() - INTERVAL '$1 days';"
        await conn.execute(query, days_to_keep)