from fastapi import (
    APIRouter, 
    status, 
    Request, 
    Path, 
    Depends, 
    Query
)
from src.schemas.pagination import Pagination
from src.schemas.log import SystemLogResponse
from src.dependencies import get_limiter
from src.exceptions import ResourceNotFoundException
from src.tables import logs as logs_table
from asyncpg import Connection
from typing import Optional
from uuid import UUID
from src.db import db_connection


router = APIRouter(prefix="/logs")
limiter = get_limiter()


@router.get("", status_code=status.HTTP_200_OK, response_model=Pagination[SystemLogResponse])
@limiter.limit("32/minute")
async def list_logs(
    request: Request,
    limit: int = Query(
        default=32, 
        ge=1, 
        le=64,
        title="Pagination Limit",
        description="Maximum number of logs to return per page."
    ),
    offset: int = Query(
        default=0, 
        ge=0,
        title="Pagination Offset",
        description="Number of logs to skip before starting to collect the result set."
    ),
    error_level: Optional[str] = Query(
        default=None, 
        title="Error Level",
        description="Filter by the severity of the log (e.g., ERROR, WARNING, CRITICAL, INFO)."
    ),
    error_type: Optional[str] = Query(
        default=None, 
        title="Error Type",
        description="Exact match for the Python exception type or custom error category."
    ),
    user_id: Optional[UUID] = Query(
        default=None, 
        title="User ID Filter",
        description="Filter logs generated by a specific user's UUID."
    ),
    conn: Connection = Depends(db_connection)
):
    """
    Retrieves a paginated list of system and error logs.
    Supports filtering by severity level, error type, and specific users.
    """
    return await logs_table.get_logs(
        limit=limit,
        offset=offset,
        conn=conn,
        error_level=error_level,
        user_id=user_id,
        error_type=error_type
    )
    

@router.get("/{log_id}", response_model=SystemLogResponse)
@limiter.limit("16/minute")
async def get_log_details(
    request: Request,
    log_id: UUID = Path(
        ...,
        title="Log ID",
        description="The unique UUID of the specific system log entry to retrieve."
    ),
    conn: Connection = Depends(db_connection)
):
    """
    Retrieves the complete details of a specific system log entry by its ID.
    """
    log: SystemLogResponse | None = await logs_table.get_log_by_id(log_id, conn)
    if not log: raise ResourceNotFoundException("Log entry")
    return log


@router.delete("", status_code=status.HTTP_200_OK)
@limiter.limit("16/minute")
async def clear_old_logs(
    request: Request,
    days_to_keep: int = Query(
        default=30, 
        ge=0, 
        description="Delete logs older than this many days. Use 0 to delete all logs."
    ),
    conn: Connection = Depends(db_connection)
) -> dict:
    """
    Deletes old system logs and returns the amount of records that were deleted.
    """
    deleted_count = await logs_table.delete_logs(days_to_keep, conn)    
    return {
        "message": "Logs cleaned up successfully.",
        "deleted_count": deleted_count,
        "days_kept": days_to_keep
    }


@router.delete("/{log_id}", status_code=status.HTTP_204_NO_CONTENT)
@limiter.limit("16/minute")
async def delete_log(
    request: Request, 
    log_id: UUID = Path(
        ...,
        title="Log ID",
        description="The unique UUID of the specific system log entry to delete."
    ), 
    conn: Connection = Depends(db_connection)
):
    """
    Permanently deletes a specific system log entry by its ID.
    """    
    deleted: bool = await logs_table.delete_log_by_id(
        log_id=log_id, 
        conn=conn
    )
        
    if not deleted:
        raise ResourceNotFoundException("Log entry")
    
